import { CountryVisaInfo } from "../model/CountryVisaInfo";

export const VISA_DATA: CountryVisaInfo[] = [
  new CountryVisaInfo('Japan', 1, 193, 0, 6, 'japan'),
  new CountryVisaInfo('Germany', 2, 191, 1, 5, 'germany'),
  new CountryVisaInfo('United States', 7, 187, 4, 10, 'united_states'),
  new CountryVisaInfo('Canada', 8, 186, 5, 10, 'canada'),
  new CountryVisaInfo('Turkey', 54, 110, 55, 28, 'turkey'),
  new CountryVisaInfo('China', 62, 80, 70, 40, 'china'),
]